feat/location 추가 문제 해결
Media-XI/artscope-backend pull request #122
Opened 2024-01-13 06:58 UTC by haroya01

- location table에 생성자, 생성일, 수정일이 추가되었습니다.
- 생성자와 관리자는 location을 수정 및 삭제할 수 있게 추가했습니다.

- location을 상세 조회할 때 작성자 정보를 반환하도록 추가했습니다.

- event에 관하여 username(작성자)으로 찾을 수 있도록 추가했습니다.
- location에 관하여 username(작성자)으로 찾을 수 있도록 추가했습니다.

2024-01-13 09:07 UTC, Hoon9901 requested changes

2024-01-13 09:07 UTC, Hoon9901 commented on src/test/java/com/example/codebase/controller/LocationControllerTest.java
> +    @DisplayName("장소 수정 테스트")
장소 수정 테스트 -> 장소 수정 시

2024-01-13 09:07 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/event/repository/EventRepository.java
> +    @Query("SELECT e FROM Event e JOIN e.member m WHERE (:username IS NULL OR m.username = :username) AND e.startDate >= :startDate AND e.endDate <= :endDate"
FULL JOIN 을 하는이유가 있나요?

Event 아닌 사용자도 함께 조회됩니다.

2024-01-13 09:09 UTC, Hoon9901 commented
PR 을 쪼개주세요. 리뷰하기 힘듭니다.

2024-01-15 04:51 UTC, haroya01 commented on src/main/java/com/example/codebase/domain/location/entity/Location.java
> +    @OneToMany(mappedBy = "location", cascade = CascadeType.ALL)
https://github.com/Media-XI/artscope-backend/pull/122/commits/fe214d085473ad82db86f2223042c93ac0399278

수정했습니다.

2024-01-15 04:52 UTC, haroya01 commented on src/main/java/com/example/codebase/domain/location/entity/Location.java
> +    public void update(LocationUpdateDTO dto) {
https://github.com/Media-XI/artscope-backend/pull/122/commits/cbbb90b2480901e1ec6679b5df76bca5fa34669b

넵 LocalDateTime.now()를 사용하도록 수정했습니다.

2024-01-15 04:53 UTC, haroya01 commented on src/main/java/com/example/codebase/domain/location/repository/LocationRepository.java
> +    @Query("SELECT l FROM Location l LEFT JOIN l.member m WHERE "
https://github.com/Media-XI/artscope-backend/pull/122/commits/fd6cf04b524bde91a020902f8b4b8b32e51e5458

쿼리를 올바르게 수정했습니다.

2024-01-15 04:56 UTC, haroya01 commented on src/main/java/com/example/codebase/controller/LocationController.java
> +        LocationsSearchResponseDTO searchResponseDTO = locationService.findLocationByUsernameAndKeyword(username, keyword, page, size);
https://github.com/Media-XI/artscope-backend/pull/122/commits/fd6cf04b524bde91a020902f8b4b8b32e51e5458

- 메서드 명을 searchLocation 으로 수정했습니다.

2024-01-15 04:58 UTC, haroya01 commented on src/main/java/com/example/codebase/domain/location/repository/LocationRepository.java
> +    @Query("SELECT l FROM Location l LEFT JOIN l.member m WHERE "
https://github.com/Media-XI/artscope-backend/pull/122/commits/fd6cf04b524bde91a020902f8b4b8b32e51e5458

- keyword만 파라미터로 받도록 하고 쿼리를 수정했습니다.

2024-01-15 06:35 UTC, Hoon9901 requested changes

2024-01-15 06:35 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/event/service/EventService.java
> +        event.update(dto, location);
현재 리팩터링 된 코드의 문제점은 다음과 같습니다.

- findLocationByLocationId 는 location 이 없을때 예외를 발생하기 때문에 orElse(null) 까지 스트림이 작동하지 않는다.
- orElse(null)은 의미없는 코드이고 따라서 Optional.ofNullable을 이용한것은 이전 if 문으로 null 체크하는거나 다름없다.
- (중요) location과 event는 **양방향 매핑**이기 location에서 연관된 event를 조회할 때  다른 location을 가지는 event가 조회 될  가능성이 있습니다. 때문에 관련 location 과 event 관계를 제거하고 Update 해야합니다.

즉
```
Location newLocation = findByLocation(10); // 10번 조회
Location oldLocation = event.getLocation(); // 이전 장소는 1번일때

// event의 location update
oldLocation.remove(event); // 이전 event 와 location 매핑 제거
newLocation.add(event); // 새로운 location - event 매핑 추가
event.locatioon = newLocation; // 객체 참조 -> 기존 update 내부 로직

...
```

2024-01-15 06:35 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/event/repository/EventRepository.java
> +    @Query("SELECT e FROM Event e LEFT JOIN e.member m WHERE " +
ON 절 없어도 작동하지만 LocationRepository에서는 ON 절을 명시했는데
일관적으로 명시할지, 안할지 필요합니다.

다른 repository 에서는 JOIN 시 ON 절을 명시하므로 ON 절을 추가해주세요

2024-01-15 06:42 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/event/service/EventService.java
> +        event.update(dto, location);
update 양방향 매핑 코드가 작성되어있었네용
이전 코드를 보고 리뷰를 했습니다..

다음 2가지 사항만 고려하시면 되겠습니다.

1. findLocationByLocationId 는 location 이 없을때 예외를 발생하기 때문에 orElse(null) 까지 스트림이 작동하지 않는다.
2. orElse(null)은 의미없는 코드이고 따라서 Optional.ofNullable을 이용한것은 이전 if 문으로 null 체크하는거나 다름없다.

2024-01-15 08:48 UTC, Hoon9901 approved these changes

2024-01-15 09:15 UTC, merged