Artdev 135 be 알람 기능
Media-XI/artscope-backend pull request #127
Opened 2024-02-17 05:22 UTC by haroya01

- 알림 목록, 알림 환경 설정 관련 api 구현 

- 알림 연결 api 구현 
   -  알림은 sse 방식으로 동작

- 다른 도메인에서 알림 기능 필요시 NotifitcaitonType.class에서 정의하고 사용
    -  알림은 Notificationsend.class를 주입하면 됩니다.

2024-02-20 13:56 UTC, Hoon9901 requested changes
알림 서비스가 드디어 구현되니 좋습니다 고생하셨어요

하지만 로직이 복잡하다 보니 코드 스타일이 몇군데 빠진게 있거나 
로직 흐름 상 문제가 되는 부분이 있는데요

확인하시고 수정부탁드려용

2024-02-20 13:56 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/notification/service/NotificationSettingService.java
> +        NotificationType type = NotificationType.valueOf(notificationType);
valueOf는 사용자 정의 메소드가 아니므로 예외처리 시 메시지를 다양하게 보여줄 수 있도록
NotificationType.from(notifcationType); 정적 팩토리 메서드를 이용하는건 어떨까요?

2024-02-20 13:56 UTC, Hoon9901 commented on src/main/resources/db/migration/V202402080452__create_notification_setting_table.sql
> +CREATE TABLE `notification_setting`
notification_setting를 row 단으로 type 관리하는 것 보단 테이블 속성을 추가하는 식으로 type을 관리하는게 어떨까요?
일단 장점은 복합키 사용 안하고, 컬럼으로 관리하다보니 해당 테이블의 데이터 갯수가 적어지는 개선이 있습니당.

2024-02-20 13:56 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/notification/dto/MessageRequest.java
> +public class MessageRequest {
```suggestion
public class NotificationMessageRequest {
```

2024-02-20 13:56 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/notification/dto/NotificationResponse.java
> +    @Schema(description = "알림 이벤트 응답")
EventMessage는 중복되지 않는 DTO 클래스 명이지만 추후 의미가 여러 곳에서 사용될 가능성이 있어서 다음과 같이 제안드립니다~

```suggestion
    @Schema(name = "NotifcationResponse.EventMessage", description = "알림 이벤트 응답")
```

2024-02-20 13:56 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/notification/repository/NotificationSettingRepository.java
> +    @Query("SELECT n FROM NotificationSetting n LEFT JOIN Member m ON n.member = m WHERE n.member = :member")
NotificationSetting 내부에 member_id 가 있으므로 해당 LEFT JOIN은 불필요하네요!

```suggestion
    @Query("SELECT n FROM NotificationSetting n WHERE n.member = :member")
```

2024-02-20 13:56 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/notification/repository/NotificationSettingRepository.java
> +    @Query("SELECT m FROM NotificationSetting n LEFT JOIN Member m ON n.member.id = m.id WHERE n.notificationType = :notificationType AND n.isReceive = true")
```suggestion
    @Query("SELECT m FROM NotificationSetting n WHERE n.notificationType = :notificationType AND n.isReceive = true")
```

2024-02-20 13:56 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/notification/repository/NotificationSettingRepository.java
> +    @Query("SELECT n FROM NotificationSetting n LEFT JOIN Member m ON n.member = m WHERE n.member = :targetMember AND n.notificationType = :type")
```suggestion
    @Query("SELECT n FROM NotificationSetting n WHERE n.member = :targetMember AND n.notificationType = :type")
```

2024-02-20 13:56 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/notification/service/NotificationEventService.java
> +    public void upDateCountAndSend(Member member, int count) {
sendNotificationCount()메소드명이 로직상 의미가 맞는것 같아요!

```suggestion
    public void sendNotificationCount(Member member, int count) {
```

2024-02-20 13:56 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/notification/service/NotificationSendServiceImpl.java
> +    public void upDateCountAndSend(Member member, int size) {
로직이 복잡한데 간단하게 정리해보면 

size = 0 -> sse 전송 X
size < 0 -> N개 (1개 또는 전체) 읽었으므로 sse 전송 O
size > 0 -> 새로운 알림 발생 -> 알림 갯수를 증가한 값을 sse 전송 O

```
    @Override
    public void upDateCountAndSend(Member member, int size) {
        if (size != 0) {
           notificationEventService.upDateCountAndSend(member, size);
        }
    }
```
로 하면 되는데 

`notificationEventService.upDateCountAndSend(member, size);` 내부 코드가
`message.getCount() + count()` 만큼 다시 증가해 저장하므로 결국엔 size 값을 넘길땐

size 가 1씩 증가, 감소 체크를 해야하고
size() 전체 읽었으면 그만큼 -size() 를 보내야하는 로직이 됩니다!

따라서 다음 로직이면 깔끔할거같아용
```java
public class NotificationSendServiceImpl implemnt .... {
    public void resetNotificationCount(Member member) {
         notificationEventService.notificationCountReset(member); // 리셋 이벤트 발행
    }     

    @Override
    public void increeeOrDecressCount(Member member, int size) {
        if (size > 0) {
           notificationEventService.sendNotification(member, 1); // 1씩 증가
        }
        else if (size < 0) {
           notificationEventService.sendNotification(member, -1); // 1씩 감소
        }
    }
```

2024-02-20 13:56 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/notification/service/NotificationService.java
> +        notificationSendService.upDateCountAndSend(member, -notifications.size());
```suggestion
        notificationSendService. resetCount(member);
```

2024-02-20 13:56 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/notification/service/NotificationService.java
> +        notificationSendService.upDateCountAndSend(member, -1);
```suggestion
        notificationSendService.sendDecreaseCount(member);
```

2024-02-28 04:13 UTC, haroya01 commented on src/main/java/com/example/codebase/controller/NotificationController.java
> +    public ResponseEntity sendAdminNotification(@RequestBody MessageRequest messageRequest) {
말씀대로 NotificationMessageRequest가 훨씬 명확한 의미를 전달하는것 같습니다.
 NotificationMessageRequest으로 클래스 명을 변경하겠습니다.

2024-03-02 11:13 UTC, Hoon9901 approved these changes

2024-03-02 11:20 UTC, merged