Art 159 be 카테고리 계층화
Media-XI/artscope-backend pull request #154
Opened 2024-03-25 09:13 UTC by haroya01

## 📝 작업 내용
- 매거진 카테고리를 계층화 했습니다.
- 테스트 코드에서 slug unique조건으로 인해 테스트가 실패하는 문제를 해결했습니다.
- 같은 카테고리 계층에서 name이 unique할수 있도록 parent_id, name과 묶어서 unique조건을 추가했습니다.

## 🦾 연관된 이슈
> [JIRA이슈](https://mediaxi.atlassian.net/browse/ART-159)

## 💬리뷰 요구사항
- 테스트코드에서 slug와 이름의 unique조건을 보장하기 위해 [랜덤함수](https://github.com/Media-XI/artscope-backend/commit/c8fdb2145c6a3280397278f8bd015f7f47f519af) 이런식으로 작성했습니다.

2024-03-25 10:32 UTC, Hoon9901 requested changes
일부 예외처리에 대해 테스트가 진행이 안됬는데 테스트 진행하시고
코멘트 체크 바랍니다

2024-03-25 10:32 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/magazine/entity/MagazineCategory.java
> +    public void update(MagazineCategory newParent) {
부모 카테고리를 변경하는 의도를 분명하게 드러나는 메소드명이 좋을듯합니다

ex) changeParentCategory

2024-03-25 10:32 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/magazine/entity/MagazineCategory.java
> +            throw new RuntimeException("카테고리는 최대 2단계 까지만 생성 가능합니다.");
해당 예외에 대해 테스트가 필요합니다

2024-03-25 10:32 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/magazine/service/MagazineCategoryService.java
> +            throw new RuntimeException("이미 이름이나 슬러그가 중복되는 카테고리가 존재합니다.");
checkCategoryExists() 를 통해서 먼저 중복 체크를 진행하는데 별도로 예외를 던지는 이유가?

2024-03-25 10:32 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/magazine/service/MagazineCategoryService.java
> +            throw new RuntimeException("이미 이름이나 슬러그가 중복되는 카테고리가 존재합니다.");
해당 예외에 대한 테스트가 필요합니다

2024-03-25 10:32 UTC, Hoon9901 commented on src/main/java/com/example/codebase/domain/magazine/service/MagazineCategoryService.java
> +            throw new RuntimeException("해당 카테고리에 속한 매거진이 존재합니다.");
마찬가지 테스트 필요

2024-03-26 07:50 UTC, haroya01 commented on src/main/java/com/example/codebase/domain/magazine/service/MagazineCategoryService.java
> +            throw new RuntimeException("해당 카테고리에 속한 매거진이 존재합니다.");
[1064dcd](https://github.com/Media-XI/artscope-backend/pull/154/commits/1064dcd0b3a5ebd7d6e13f99721f7289040eca6b)
해당 테스트를 추가했습니다

2024-03-26 07:51 UTC, haroya01 commented on src/main/java/com/example/codebase/domain/magazine/entity/MagazineCategory.java
> +            throw new RuntimeException("카테고리는 최대 2단계 까지만 생성 가능합니다.");
[1064dcd](https://github.com/Media-XI/artscope-backend/pull/154/commits/1064dcd0b3a5ebd7d6e13f99721f7289040eca6b)
해당 예외를 검증하도록 추가했습니다

2024-03-26 07:51 UTC, haroya01 commented on src/main/java/com/example/codebase/domain/magazine/entity/MagazineCategory.java
> +    public void update(MagazineCategory newParent) {
[2b24cb8](https://github.com/Media-XI/artscope-backend/pull/154/commits/2b24cb8b8274517178fbb161ca384cda1192936d)
changeParentCategory로 조금더 의도가 분명하게 수정했습니다

2024-03-26 10:04 UTC, Hoon9901 approved these changes

2024-03-27 11:09 UTC, merged